<a href="https://colab.research.google.com/github/anshajshukla/Pytorch-/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello i'am excited to learn pytorch")

Hello i'am excited to learn pytorch


## 00. Pytorch Fundamentals

Resource Notebook :- https://www.learnpytorch.io/00_pytorch_fundamentals/


In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

torch.tensor infers the data type from the input and requires data, while torch.Tensor uses the default float type (float32), can create uninitialized tensors from shape, and is generally less recommended for new code

In [9]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as python int
scalar.item()

7

In [17]:
# Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)    # number of square brackets
print(vector.shape)   # number of pair inside the square brackets

tensor([7, 7])
1
torch.Size([2])


In [20]:
# Matrix

Matrix = torch.tensor([[7,9],
                      [9,10]])
Matrix

tensor([[ 7,  9],
        [ 9, 10]])

In [23]:
print(Matrix.ndim)
print(Matrix[0])
print(Matrix[1])
print(Matrix.shape)

2
tensor([7, 9])
tensor([ 9, 10])
torch.Size([2, 2])


In [27]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [28]:
TENSOR.ndim

3

In [38]:
print(TENSOR.shape)
# [1,3,3]?

print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][0][0])


torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


### Random Tensors

why random tensors?
Random tensors are important because the way many neural networks learn is that
they start witht tensors full of random numbersand then adjust these radom numbers to better represent the dsys

Start with random numbers --> look at the data --> update the randome numbers --> look at data ---> update the numbers

In [39]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5611, 0.9431, 0.9436, 0.8357],
        [0.9004, 0.6172, 0.4373, 0.4024],
        [0.2435, 0.2389, 0.4273, 0.1630]])

In [41]:
random_tensor.ndim

2

In [42]:
# Create a random tensor with similar image to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [46]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
ones.dtype

torch.float32

### Tensor Datatypes
**Note:**  Tensor dataypes is one of the 3 big errors you will run into with pytorch
1. tensors not right datatype
2. tensor not right shape
3. tensor not on the same device

In [52]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,5.0,6.0],dtype=torch.float16)
float_32_tensor

tensor([3., 5., 6.], dtype=torch.float16)

In [55]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,5.0,6.0],
                               dtype=None,  # what is datatype of tensor float16,float32,float64(not common)
                               device=None, # what device you tensor is on
                               requires_grad=False) # whether or not to track gradient with tensor operation
float_32_tensor.dtype

torch.float32

In [60]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype
int_16_tensor = float_32_tensor.type(torch.int16)

In [61]:
 (float_16_tensor * float_32_tensor).dtype,(int_16_tensor * float_32_tensor).dtype

(torch.float32, torch.float32)

### Getting information from tensors  (tensors attribute)
1. Tensors of not right datatype  --> tensor.dtype
2. Tensors of not right shape     --> tensor.shape
3. Tensors of not right device    --> tensor.device

### Tensors Operations

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matrix Multiplication


In [68]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [69]:
tensor.dtype

torch.int64

In [70]:
tensor*10
tensor.mul(tensor,10) # alternative

tensor([10, 20, 30])

In [71]:
tensor-1

tensor([0, 1, 2])

In [72]:
tensor/3

tensor([0.3333, 0.6667, 1.0000])

In [73]:
tensor.dtype # it doesnt change on dividing

torch.int64

### Matrix Multiplication

Two main ways of performing multiplication in neural network
1. element wise
2. matrix wise

In [79]:
 # Element wise multiplication
 print(tensor)
 print(tensor * tensor)
 print(tensor.mul(tensor))

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([1, 4, 9])


In [80]:
# matric multiplication
torch.matmul(tensor,tensor)


tensor(14)

 ### Tensor Aggregation (finding max min sum mean)

In [86]:
x = torch.arange(0,100,10)
print(x)
print(x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [83]:
# Find the min and max
print(torch.min(x))
print(torch.max(x))

tensor(0)
tensor(90)


In [91]:
# torch.mean(x) --> not a right datatype (x is int64(long) and mean only allows float32)
x = x.type(torch.float32)
torch.mean(x)


tensor(45.)

### Positional Min and Max